import PrivateRouter from './PrivateRouter'
import SessionProviderApp from './SessionProviderApp'
import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <SessionProviderApp>
            <PrivateRouter>
              {children}
            </PrivateRouter>
          </SessionProviderApp>
        </body>
    </html>
  )
}
